//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	uuid "github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// FrontendParams defines model for FrontendParams.
type FrontendParams struct {
	AuthAuthority string `json:"authAuthority"`
	AuthClientId  string `json:"authClientId"`
	AuthScope     string `json:"authScope"`
}

// Game defines model for Game.
type Game struct {
	AwayTeamId     uuid.UUID `json:"awayTeamId,omitempty"`
	AwayTeamScore  *int      `json:"awayTeamScore,omitempty"`
	AwayTeamUserId uuid.UUID `json:"awayTeamUserId,omitempty"`
	HomeTeamId     uuid.UUID `json:"homeTeamId,omitempty"`
	HomeTeamScore  *int      `json:"homeTeamScore,omitempty"`
	HomeTeamUserId uuid.UUID `json:"homeTeamUserId,omitempty"`
	Id             uuid.UUID `gorm:"primarykey" json:"id"`
	SeriesId       uuid.UUID `gorm:"index" json:"seriesId"`
}

// Series defines model for Series.
type Series struct {
	FirstTeamId     uuid.UUID `json:"firstTeamId,omitempty"`
	FirstTeamScore  *int      `json:"firstTeamScore,omitempty"`
	FirstTeamUserId uuid.UUID `json:"firstTeamUserId,omitempty"`
	Id              uuid.UUID `gorm:"primarykey" json:"id"`

	// Round round number that this series is a part of (0, 1, 2)
	Round            int       `json:"round"`
	SecondTeamId     uuid.UUID `json:"secondTeamId,omitempty"`
	SecondTeamScore  *int      `json:"secondTeamScore,omitempty"`
	SecondTeamUserId uuid.UUID `json:"secondTeamUserId,omitempty"`
	TournamentId     uuid.UUID `gorm:"index" json:"tournamentId"`
}

// Team defines model for Team.
type Team struct {
	Id   uuid.UUID `gorm:"primarykey" json:"id"`
	Name string    `json:"name"`
	Slug string    `json:"slug"`
}

// Tournament defines model for Tournament.
type Tournament struct {
	Id   uuid.UUID `gorm:"primarykey" json:"id"`
	Name string    `json:"name"`
}

// User defines model for User.
type User struct {
	Id        uuid.UUID `gorm:"primarykey" json:"id"`
	Name      string    `json:"name"`
	Shortname string    `json:"shortname"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// ServerError defines model for ServerError.
type ServerError = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// CreateGameJSONRequestBody defines body for CreateGame for application/json ContentType.
type CreateGameJSONRequestBody = Game

// UpdateGameByIdJSONRequestBody defines body for UpdateGameById for application/json ContentType.
type UpdateGameByIdJSONRequestBody = Game

// CreateSeriesJSONRequestBody defines body for CreateSeries for application/json ContentType.
type CreateSeriesJSONRequestBody = Series

// UpdateSeriesByIdJSONRequestBody defines body for UpdateSeriesById for application/json ContentType.
type UpdateSeriesByIdJSONRequestBody = Series

// CreateTeamJSONRequestBody defines body for CreateTeam for application/json ContentType.
type CreateTeamJSONRequestBody = Team

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = User

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create game
	// (POST /games)
	CreateGame(w http.ResponseWriter, r *http.Request)
	// Get games
	// (GET /games/{gameId})
	GetGameById(w http.ResponseWriter, r *http.Request, gameId uuid.UUID)
	// Update an existing game
	// (PUT /games/{gameId})
	UpdateGameById(w http.ResponseWriter, r *http.Request, gameId uuid.UUID)
	// Get frontend params
	// (GET /params)
	GetFrontendParams(w http.ResponseWriter, r *http.Request)
	// Create series
	// (POST /series)
	CreateSeries(w http.ResponseWriter, r *http.Request)
	// Get series
	// (GET /series/{seriesId})
	GetSeriesById(w http.ResponseWriter, r *http.Request, seriesId uuid.UUID)
	// Update series
	// (PUT /series/{seriesId})
	UpdateSeriesById(w http.ResponseWriter, r *http.Request, seriesId uuid.UUID)
	// Get teams
	// (GET /teams)
	GetTeams(w http.ResponseWriter, r *http.Request)
	// Create team
	// (POST /teams)
	CreateTeam(w http.ResponseWriter, r *http.Request)
	// Get tournaments
	// (GET /tournaments)
	GetTournaments(w http.ResponseWriter, r *http.Request)
	// Get games
	// (GET /tournaments/{tournamentId}/games)
	GetGamesByTournamentId(w http.ResponseWriter, r *http.Request, tournamentId uuid.UUID)
	// Get tournament series
	// (GET /tournaments/{tournamentId}/series)
	GetSeriesByTournamentId(w http.ResponseWriter, r *http.Request, tournamentId uuid.UUID)
	// Get users
	// (GET /users)
	GetUsers(w http.ResponseWriter, r *http.Request)
	// Create user
	// (POST /users)
	CreateUser(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateGame operation middleware
func (siw *ServerInterfaceWrapper) CreateGame(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGame(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGameById operation middleware
func (siw *ServerInterfaceWrapper) GetGameById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId uuid.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", r.PathValue("gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGameById(w, r, gameId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateGameById operation middleware
func (siw *ServerInterfaceWrapper) UpdateGameById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId uuid.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", r.PathValue("gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateGameById(w, r, gameId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFrontendParams operation middleware
func (siw *ServerInterfaceWrapper) GetFrontendParams(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFrontendParams(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSeries operation middleware
func (siw *ServerInterfaceWrapper) CreateSeries(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSeries(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSeriesById operation middleware
func (siw *ServerInterfaceWrapper) GetSeriesById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "seriesId" -------------
	var seriesId uuid.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "seriesId", r.PathValue("seriesId"), &seriesId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "seriesId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSeriesById(w, r, seriesId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSeriesById operation middleware
func (siw *ServerInterfaceWrapper) UpdateSeriesById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "seriesId" -------------
	var seriesId uuid.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "seriesId", r.PathValue("seriesId"), &seriesId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "seriesId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSeriesById(w, r, seriesId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTeams operation middleware
func (siw *ServerInterfaceWrapper) GetTeams(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTeams(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTeam operation middleware
func (siw *ServerInterfaceWrapper) CreateTeam(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTeam(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTournaments operation middleware
func (siw *ServerInterfaceWrapper) GetTournaments(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTournaments(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGamesByTournamentId operation middleware
func (siw *ServerInterfaceWrapper) GetGamesByTournamentId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tournamentId" -------------
	var tournamentId uuid.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tournamentId", r.PathValue("tournamentId"), &tournamentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tournamentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGamesByTournamentId(w, r, tournamentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSeriesByTournamentId operation middleware
func (siw *ServerInterfaceWrapper) GetSeriesByTournamentId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tournamentId" -------------
	var tournamentId uuid.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tournamentId", r.PathValue("tournamentId"), &tournamentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tournamentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSeriesByTournamentId(w, r, tournamentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/games", wrapper.CreateGame)
	m.HandleFunc("GET "+options.BaseURL+"/games/{gameId}", wrapper.GetGameById)
	m.HandleFunc("PUT "+options.BaseURL+"/games/{gameId}", wrapper.UpdateGameById)
	m.HandleFunc("GET "+options.BaseURL+"/params", wrapper.GetFrontendParams)
	m.HandleFunc("POST "+options.BaseURL+"/series", wrapper.CreateSeries)
	m.HandleFunc("GET "+options.BaseURL+"/series/{seriesId}", wrapper.GetSeriesById)
	m.HandleFunc("PUT "+options.BaseURL+"/series/{seriesId}", wrapper.UpdateSeriesById)
	m.HandleFunc("GET "+options.BaseURL+"/teams", wrapper.GetTeams)
	m.HandleFunc("POST "+options.BaseURL+"/teams", wrapper.CreateTeam)
	m.HandleFunc("GET "+options.BaseURL+"/tournaments", wrapper.GetTournaments)
	m.HandleFunc("GET "+options.BaseURL+"/tournaments/{tournamentId}/games", wrapper.GetGamesByTournamentId)
	m.HandleFunc("GET "+options.BaseURL+"/tournaments/{tournamentId}/series", wrapper.GetSeriesByTournamentId)
	m.HandleFunc("GET "+options.BaseURL+"/users", wrapper.GetUsers)
	m.HandleFunc("POST "+options.BaseURL+"/users", wrapper.CreateUser)

	return m
}

type BadRequestJSONResponse Error

type ServerErrorJSONResponse Error

type UnauthorizedJSONResponse Error

type CreateGameRequestObject struct {
	Body *CreateGameJSONRequestBody
}

type CreateGameResponseObject interface {
	VisitCreateGameResponse(w http.ResponseWriter) error
}

type CreateGame201JSONResponse struct {
	Game Game `json:"game"`
}

func (response CreateGame201JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateGame400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateGame400JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateGame401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateGame401JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateGame500JSONResponse struct{ ServerErrorJSONResponse }

func (response CreateGame500JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetGameByIdRequestObject struct {
	GameId uuid.UUID `json:"gameId"`
}

type GetGameByIdResponseObject interface {
	VisitGetGameByIdResponse(w http.ResponseWriter) error
}

type GetGameById200JSONResponse struct {
	Game Game `json:"game"`
}

func (response GetGameById200JSONResponse) VisitGetGameByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetGameById400JSONResponse struct{ BadRequestJSONResponse }

func (response GetGameById400JSONResponse) VisitGetGameByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetGameById500JSONResponse struct{ ServerErrorJSONResponse }

func (response GetGameById500JSONResponse) VisitGetGameByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateGameByIdRequestObject struct {
	GameId uuid.UUID `json:"gameId"`
	Body   *UpdateGameByIdJSONRequestBody
}

type UpdateGameByIdResponseObject interface {
	VisitUpdateGameByIdResponse(w http.ResponseWriter) error
}

type UpdateGameById200JSONResponse struct {
	Game Game `json:"game"`
}

func (response UpdateGameById200JSONResponse) VisitUpdateGameByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateGameById400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateGameById400JSONResponse) VisitUpdateGameByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateGameById401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateGameById401JSONResponse) VisitUpdateGameByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateGameById500JSONResponse struct{ ServerErrorJSONResponse }

func (response UpdateGameById500JSONResponse) VisitUpdateGameByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetFrontendParamsRequestObject struct {
}

type GetFrontendParamsResponseObject interface {
	VisitGetFrontendParamsResponse(w http.ResponseWriter) error
}

type GetFrontendParams200JSONResponse struct {
	Params FrontendParams `json:"params"`
}

func (response GetFrontendParams200JSONResponse) VisitGetFrontendParamsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetFrontendParams500JSONResponse struct{ ServerErrorJSONResponse }

func (response GetFrontendParams500JSONResponse) VisitGetFrontendParamsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateSeriesRequestObject struct {
	Body *CreateSeriesJSONRequestBody
}

type CreateSeriesResponseObject interface {
	VisitCreateSeriesResponse(w http.ResponseWriter) error
}

type CreateSeries201JSONResponse struct {
	Series Series `json:"series"`
}

func (response CreateSeries201JSONResponse) VisitCreateSeriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateSeries400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateSeries400JSONResponse) VisitCreateSeriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateSeries401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateSeries401JSONResponse) VisitCreateSeriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateSeries500JSONResponse struct{ ServerErrorJSONResponse }

func (response CreateSeries500JSONResponse) VisitCreateSeriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSeriesByIdRequestObject struct {
	SeriesId uuid.UUID `json:"seriesId"`
}

type GetSeriesByIdResponseObject interface {
	VisitGetSeriesByIdResponse(w http.ResponseWriter) error
}

type GetSeriesById200JSONResponse struct {
	Games  []Game `json:"games"`
	Series Series `json:"series"`
}

func (response GetSeriesById200JSONResponse) VisitGetSeriesByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSeriesById400JSONResponse struct{ BadRequestJSONResponse }

func (response GetSeriesById400JSONResponse) VisitGetSeriesByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetSeriesById500JSONResponse struct{ ServerErrorJSONResponse }

func (response GetSeriesById500JSONResponse) VisitGetSeriesByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSeriesByIdRequestObject struct {
	SeriesId uuid.UUID `json:"seriesId"`
	Body     *UpdateSeriesByIdJSONRequestBody
}

type UpdateSeriesByIdResponseObject interface {
	VisitUpdateSeriesByIdResponse(w http.ResponseWriter) error
}

type UpdateSeriesById200JSONResponse struct {
	Series Series `json:"series"`
}

func (response UpdateSeriesById200JSONResponse) VisitUpdateSeriesByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSeriesById400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateSeriesById400JSONResponse) VisitUpdateSeriesByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSeriesById401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateSeriesById401JSONResponse) VisitUpdateSeriesByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSeriesById500JSONResponse struct{ ServerErrorJSONResponse }

func (response UpdateSeriesById500JSONResponse) VisitUpdateSeriesByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTeamsRequestObject struct {
}

type GetTeamsResponseObject interface {
	VisitGetTeamsResponse(w http.ResponseWriter) error
}

type GetTeams200JSONResponse struct {
	Teams []Team `json:"teams"`
}

func (response GetTeams200JSONResponse) VisitGetTeamsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTeams400JSONResponse struct{ BadRequestJSONResponse }

func (response GetTeams400JSONResponse) VisitGetTeamsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetTeams500JSONResponse struct{ ServerErrorJSONResponse }

func (response GetTeams500JSONResponse) VisitGetTeamsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateTeamRequestObject struct {
	Body *CreateTeamJSONRequestBody
}

type CreateTeamResponseObject interface {
	VisitCreateTeamResponse(w http.ResponseWriter) error
}

type CreateTeam201JSONResponse struct {
	Team Team `json:"team"`
}

func (response CreateTeam201JSONResponse) VisitCreateTeamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTeam400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateTeam400JSONResponse) VisitCreateTeamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateTeam401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateTeam401JSONResponse) VisitCreateTeamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateTeam500JSONResponse struct{ ServerErrorJSONResponse }

func (response CreateTeam500JSONResponse) VisitCreateTeamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTournamentsRequestObject struct {
}

type GetTournamentsResponseObject interface {
	VisitGetTournamentsResponse(w http.ResponseWriter) error
}

type GetTournaments200JSONResponse struct {
	Tournaments []Tournament `json:"tournaments"`
}

func (response GetTournaments200JSONResponse) VisitGetTournamentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTournaments400JSONResponse struct{ BadRequestJSONResponse }

func (response GetTournaments400JSONResponse) VisitGetTournamentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetTournaments500JSONResponse struct{ ServerErrorJSONResponse }

func (response GetTournaments500JSONResponse) VisitGetTournamentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetGamesByTournamentIdRequestObject struct {
	TournamentId uuid.UUID `json:"tournamentId"`
}

type GetGamesByTournamentIdResponseObject interface {
	VisitGetGamesByTournamentIdResponse(w http.ResponseWriter) error
}

type GetGamesByTournamentId200JSONResponse struct {
	Games []Game `json:"games"`
}

func (response GetGamesByTournamentId200JSONResponse) VisitGetGamesByTournamentIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetGamesByTournamentId400JSONResponse struct{ BadRequestJSONResponse }

func (response GetGamesByTournamentId400JSONResponse) VisitGetGamesByTournamentIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetGamesByTournamentId500JSONResponse struct{ ServerErrorJSONResponse }

func (response GetGamesByTournamentId500JSONResponse) VisitGetGamesByTournamentIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSeriesByTournamentIdRequestObject struct {
	TournamentId uuid.UUID `json:"tournamentId"`
}

type GetSeriesByTournamentIdResponseObject interface {
	VisitGetSeriesByTournamentIdResponse(w http.ResponseWriter) error
}

type GetSeriesByTournamentId200JSONResponse struct {
	Series []Series `json:"series"`
}

func (response GetSeriesByTournamentId200JSONResponse) VisitGetSeriesByTournamentIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSeriesByTournamentId400JSONResponse struct{ BadRequestJSONResponse }

func (response GetSeriesByTournamentId400JSONResponse) VisitGetSeriesByTournamentIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetSeriesByTournamentId500JSONResponse struct{ ServerErrorJSONResponse }

func (response GetSeriesByTournamentId500JSONResponse) VisitGetSeriesByTournamentIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersRequestObject struct {
}

type GetUsersResponseObject interface {
	VisitGetUsersResponse(w http.ResponseWriter) error
}

type GetUsers200JSONResponse struct {
	Users []User `json:"users"`
}

func (response GetUsers200JSONResponse) VisitGetUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUsers400JSONResponse struct{ BadRequestJSONResponse }

func (response GetUsers400JSONResponse) VisitGetUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetUsers500JSONResponse struct{ ServerErrorJSONResponse }

func (response GetUsers500JSONResponse) VisitGetUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateUserRequestObject struct {
	Body *CreateUserJSONRequestBody
}

type CreateUserResponseObject interface {
	VisitCreateUserResponse(w http.ResponseWriter) error
}

type CreateUser201JSONResponse struct {
	User User `json:"user"`
}

func (response CreateUser201JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateUser400JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateUser401JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser500JSONResponse struct{ ServerErrorJSONResponse }

func (response CreateUser500JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create game
	// (POST /games)
	CreateGame(ctx context.Context, request CreateGameRequestObject) (CreateGameResponseObject, error)
	// Get games
	// (GET /games/{gameId})
	GetGameById(ctx context.Context, request GetGameByIdRequestObject) (GetGameByIdResponseObject, error)
	// Update an existing game
	// (PUT /games/{gameId})
	UpdateGameById(ctx context.Context, request UpdateGameByIdRequestObject) (UpdateGameByIdResponseObject, error)
	// Get frontend params
	// (GET /params)
	GetFrontendParams(ctx context.Context, request GetFrontendParamsRequestObject) (GetFrontendParamsResponseObject, error)
	// Create series
	// (POST /series)
	CreateSeries(ctx context.Context, request CreateSeriesRequestObject) (CreateSeriesResponseObject, error)
	// Get series
	// (GET /series/{seriesId})
	GetSeriesById(ctx context.Context, request GetSeriesByIdRequestObject) (GetSeriesByIdResponseObject, error)
	// Update series
	// (PUT /series/{seriesId})
	UpdateSeriesById(ctx context.Context, request UpdateSeriesByIdRequestObject) (UpdateSeriesByIdResponseObject, error)
	// Get teams
	// (GET /teams)
	GetTeams(ctx context.Context, request GetTeamsRequestObject) (GetTeamsResponseObject, error)
	// Create team
	// (POST /teams)
	CreateTeam(ctx context.Context, request CreateTeamRequestObject) (CreateTeamResponseObject, error)
	// Get tournaments
	// (GET /tournaments)
	GetTournaments(ctx context.Context, request GetTournamentsRequestObject) (GetTournamentsResponseObject, error)
	// Get games
	// (GET /tournaments/{tournamentId}/games)
	GetGamesByTournamentId(ctx context.Context, request GetGamesByTournamentIdRequestObject) (GetGamesByTournamentIdResponseObject, error)
	// Get tournament series
	// (GET /tournaments/{tournamentId}/series)
	GetSeriesByTournamentId(ctx context.Context, request GetSeriesByTournamentIdRequestObject) (GetSeriesByTournamentIdResponseObject, error)
	// Get users
	// (GET /users)
	GetUsers(ctx context.Context, request GetUsersRequestObject) (GetUsersResponseObject, error)
	// Create user
	// (POST /users)
	CreateUser(ctx context.Context, request CreateUserRequestObject) (CreateUserResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateGame operation middleware
func (sh *strictHandler) CreateGame(w http.ResponseWriter, r *http.Request) {
	var request CreateGameRequestObject

	var body CreateGameJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateGame(ctx, request.(CreateGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateGame")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateGameResponseObject); ok {
		if err := validResponse.VisitCreateGameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGameById operation middleware
func (sh *strictHandler) GetGameById(w http.ResponseWriter, r *http.Request, gameId uuid.UUID) {
	var request GetGameByIdRequestObject

	request.GameId = gameId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGameById(ctx, request.(GetGameByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGameById")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGameByIdResponseObject); ok {
		if err := validResponse.VisitGetGameByIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateGameById operation middleware
func (sh *strictHandler) UpdateGameById(w http.ResponseWriter, r *http.Request, gameId uuid.UUID) {
	var request UpdateGameByIdRequestObject

	request.GameId = gameId

	var body UpdateGameByIdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateGameById(ctx, request.(UpdateGameByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateGameById")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateGameByIdResponseObject); ok {
		if err := validResponse.VisitUpdateGameByIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFrontendParams operation middleware
func (sh *strictHandler) GetFrontendParams(w http.ResponseWriter, r *http.Request) {
	var request GetFrontendParamsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFrontendParams(ctx, request.(GetFrontendParamsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFrontendParams")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFrontendParamsResponseObject); ok {
		if err := validResponse.VisitGetFrontendParamsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSeries operation middleware
func (sh *strictHandler) CreateSeries(w http.ResponseWriter, r *http.Request) {
	var request CreateSeriesRequestObject

	var body CreateSeriesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSeries(ctx, request.(CreateSeriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSeries")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSeriesResponseObject); ok {
		if err := validResponse.VisitCreateSeriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSeriesById operation middleware
func (sh *strictHandler) GetSeriesById(w http.ResponseWriter, r *http.Request, seriesId uuid.UUID) {
	var request GetSeriesByIdRequestObject

	request.SeriesId = seriesId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSeriesById(ctx, request.(GetSeriesByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSeriesById")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSeriesByIdResponseObject); ok {
		if err := validResponse.VisitGetSeriesByIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateSeriesById operation middleware
func (sh *strictHandler) UpdateSeriesById(w http.ResponseWriter, r *http.Request, seriesId uuid.UUID) {
	var request UpdateSeriesByIdRequestObject

	request.SeriesId = seriesId

	var body UpdateSeriesByIdJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSeriesById(ctx, request.(UpdateSeriesByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSeriesById")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateSeriesByIdResponseObject); ok {
		if err := validResponse.VisitUpdateSeriesByIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTeams operation middleware
func (sh *strictHandler) GetTeams(w http.ResponseWriter, r *http.Request) {
	var request GetTeamsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTeams(ctx, request.(GetTeamsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTeams")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTeamsResponseObject); ok {
		if err := validResponse.VisitGetTeamsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTeam operation middleware
func (sh *strictHandler) CreateTeam(w http.ResponseWriter, r *http.Request) {
	var request CreateTeamRequestObject

	var body CreateTeamJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTeam(ctx, request.(CreateTeamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTeam")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTeamResponseObject); ok {
		if err := validResponse.VisitCreateTeamResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTournaments operation middleware
func (sh *strictHandler) GetTournaments(w http.ResponseWriter, r *http.Request) {
	var request GetTournamentsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTournaments(ctx, request.(GetTournamentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTournaments")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTournamentsResponseObject); ok {
		if err := validResponse.VisitGetTournamentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGamesByTournamentId operation middleware
func (sh *strictHandler) GetGamesByTournamentId(w http.ResponseWriter, r *http.Request, tournamentId uuid.UUID) {
	var request GetGamesByTournamentIdRequestObject

	request.TournamentId = tournamentId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGamesByTournamentId(ctx, request.(GetGamesByTournamentIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGamesByTournamentId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGamesByTournamentIdResponseObject); ok {
		if err := validResponse.VisitGetGamesByTournamentIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSeriesByTournamentId operation middleware
func (sh *strictHandler) GetSeriesByTournamentId(w http.ResponseWriter, r *http.Request, tournamentId uuid.UUID) {
	var request GetSeriesByTournamentIdRequestObject

	request.TournamentId = tournamentId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSeriesByTournamentId(ctx, request.(GetSeriesByTournamentIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSeriesByTournamentId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSeriesByTournamentIdResponseObject); ok {
		if err := validResponse.VisitGetSeriesByTournamentIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUsers operation middleware
func (sh *strictHandler) GetUsers(w http.ResponseWriter, r *http.Request) {
	var request GetUsersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsers(ctx, request.(GetUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUsersResponseObject); ok {
		if err := validResponse.VisitGetUsersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateUser operation middleware
func (sh *strictHandler) CreateUser(w http.ResponseWriter, r *http.Request) {
	var request CreateUserRequestObject

	var body CreateUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUser(ctx, request.(CreateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateUserResponseObject); ok {
		if err := validResponse.VisitCreateUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaXW/bNhT9KwS3hw2QLafbgEJvSbsG3jC0aBLsIcgDI13LbC2SIyk3XuD/PvBDX5Zk",
	"K52dxkmfEonk5eW9h4eHV77HMc8EZ8C0wtE9lqAEZwrswxlJPsI/OShtnmLONDD7LxFiQWOiKWfhJ8WZ",
	"eafiOWTE/PejhBmO8A9hZTp0rSr8XUou8Xq9DnACKpZUGCM4wqcoXlBgGimaALolCZJuagRuSIAvQC5B",
	"OguP4I+y07npEY/jXEpIjB9XjOR6ziX9F5LDO/IXVYqyFHGJKFuSBU2QmR5p/hkYNv29CTNDGRwhuQCp",
	"qUtkzBMwf/VKAI4wZRpSsDHNQCmS1huVlpSl1rDJADWLjq6diar/TVD057efINbG1jtpA5F8IJJkqu2F",
	"cfvURU6vOmYMbI83FgbTpLfDRczFAIebs23YrlvqWso5yaBjAV/I6hJI5pybcZkRjSOc59RYbLoT4LtR",
	"ykf+pekyvrqavq2/H9FMcGlxw+x8hSVB9BxHOKV6nt+OY56FKefpAkLbvq6bUJ+pGHGLFbIYCW5SK3Gk",
	"ZQ4mXN7hi5jLHgAUXa4UyKNZ15xncFSJKBzekoiiy1Elgn57RzkRdGTYKQU2gjstyUiT1O7XlMsMR1hI",
	"mhG5+gwrR5cgKajpMXhOWQJ37lCoU5tzlefSTOn5rFxVF51d2MY2oc2oVPqoNlLp8ZadVPb5vpUOvJUk",
	"z5l1uylZ7GvE8uwWJNJzopGeU4UcRBFViCBBpEZ8hn6aBOgkQK9+rtZay6SCmLPkqABaubwFoVWno4Jo",
	"g3KeFXs6IHdRp0lSmziPcbMyr2lbolot8nS3nrZ+WRt+RGe0yrA+65j1hqYrJmaLP3cEzbnUD41VfVg7",
	"bo4lc3N5uzD3W1+RACJBmmudebq1T++KGP7x9yX2t2FjybVWQZ1rLRwbUDbj7VPr9MMU5QoSdLtCeg5o",
	"5q+zxgLVC2OigrdCpx+mOMBLkMoNn4xPxhMTDC6AEUFxhH8ZT8YTnwvrfpgSvxDBXVGl6cIbCUQDIih1",
	"ATKAscUEw7e+9dw1+erIGU9We6tBWNMdJYjSLQZfCteqnPrDoVE5ejU5eZBXzb2ReiQN8LUJrrQHSz0r",
	"svvg18mkb65ySWGtEmaHnOwe0qgSrQP825B56iWu+hbA0XUT/Nc365sAqzwz+7NKkU+O28bXtoyh8I2x",
	"5KAX3ps/02RtwwwdEPwIOpdMeQyavTB9O25B8Ry0sX22mjqukSQDDVJZP5sGp2+NzvOOUfPGUlPBJtg5",
	"1EJUUEPHN2PJtQnyBrAnTxrY7//8Skx/HTxL/J2DRo7c2ugLsMg7kHYlEssqDMEdVZqytJv2XL8XBLfH",
	"I/b+FOyi92e6C54gs/fnqIvlRVl772R3s02r7dMnd1pcv1HZ3ysaKo+34WHDg01keCPDsbEHuisChkQR",
	"lSIhhbM+J6qqvm1Xfb5jt+67KBoPQRDe+C7tp+o+HEr9VeEa5HETCH7wS9aAZZIKOPpQ1cEY3hf14iFK",
	"cEGVLdb5Al6/JnQzDT+mS1c7DuqyoP1ilKGrC2jYzYbudCyXS6QkK1x+2vh/Wyfwvjx1tdkP8+F6s4dw",
	"Xc8XB+bHPFa2JeOQ2vOxDpdnqEC3nysatunO9lli+3ceIpewd41ZOjeIXW3Jv8WuG1hwJp86SWpoKlMX",
	"W0uR26WoGdgjRC9d0yH4wkV+hwjV1fyHkqDaf/QZ4GsbFS9afPrkbOLNMkRVPH8IT1SjutmiZnW/nNF0",
	"dxhzVJ+/dvJHzfyTZ5FGjMvc1lewmeHwvv6FdV19+BiYdtsfzbg0XFRa6i1Eq7PVZfOL7gDBVtntFm2b",
	"34i/30KG3EI6anbqaEvXO1BdqcmH3aAH4bq4f3wH9j5l/yBkF/p/B7Yf4z6wV/reoeFzZVE1GM22fyd2",
	"r6ylvaawdG5QBu2PLnblz5l86unLfSyLlLnYDtDwZmCPhr9yTYfQ8C7yOzR8Xs1/KA2f+5/dDPC1jYoX",
	"reF9cjbx5n87vew+eYTkSR6bB5SAWPCVP35yufC/vVFR6M5SWKmxWmo5TmAZEkHD5QleB5sGFzwmC5TA",
	"EhZcWPLSYAtFDaNRGNqOc6509HryelIavClXsGn5fbEhFCK3PN/Ut/6gqsvbtnctGyWz+uHlEbJzZKE9",
	"/EAnPQaMK3jBj3NpGjCuqAkU67SPW8f1fCb0BsqvXeub9X8BAAD//y+7ULZPNgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
